### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ringoz** [mattiasgustavsson/libs#1]
Is strpool.h thread-safe?
E.g. can we access & modify the pool concurrently?

**Comment by mattiasgustavsson** [comment]
No, it is not thread safe. If you need to use it concurrently, I'd suggest making a wrapper for it which protects access with a mutex.

 If you use different pools for different threads though, there shouldn't be a problem.

**Comment by ringoz** [comment]
Ok, thanks.
