### ISSUE TITLE
assetsys_mount should accept absolute path

### ISSUE THREAD

**Issue by isRyven** [mattiasgustavsson/libs#11]
Is there any certain motivation behind that statement?
```
assetsys_error_t assetsys_mount( assetsys_t* sys, char const* path, char const* mount_as )
...
... `path` must be a relative path ...
```

In my project i actually have to load assets from different places, eg. installation folder and folder in Documents(win) or home(linux). And calculating relative path to these is not the pleasing work to do.

This line however does permit absolute paths in windows! I can still mount any directory or archive i want having path starting with something like this `C:/Users/user/Documents/Game`.
https://github.com/mattiasgustavsson/libs/blob/022370a79cf2d5f87fb43b420834a069adb5fede/assetsys.h#L5866

But this won't work on linux, so it makes me wonder why even bother adding that line over there? I had to remove it for my project. I have to support multiple paths to the assets and relative paths are not reasonable restriction over here.

**Comment by mattiasgustavsson** [comment]
Fixed
