### ISSUE TITLE
Cast from thread_tls_t to pthread_key_t loses precision

### ISSUE THREAD

**Issue by braddabug** [mattiasgustavsson/libs#12]
I'm using g++, and I'm getting errors like this when using thread.h:

```
error: cast from ‘thread_tls_t {aka void*}’ to ‘pthread_key_t {aka unsigned int}’ loses precision [-fpermissive]
  pthread_key_delete((pthread_key_t)tls);
```
The Windows code is casting tls to uintptr_t before casting to DWORD in order to (I assume) fix a similar issue on Windows. The same fix seems to work for the Posix version in g++.

**Comment by mattiasgustavsson** [comment]
Fixed in https://github.com/mattiasgustavsson/libs/commit/56f1fe8f7af90129fe0c2e8e5d27d355cae8570f
