### ISSUE TITLE
Issue with ini_find_section and ini_find_property (+fix)

### ISSUE THREAD

**Issue by WSSDude420** [mattiasgustavsson/libs#14]
When no name_length argument is provided, you ask for string length by calling ```INI_STRLEN(name)```. 
This is actually wrong, it should be ```INI_STRLEN(name) + 1```, as you should compare it with ```'\0'``` too.

In current state, if eg. two sections are present in INI, ```[A]``` and ```[AB]```, where section ```[AB]``` comes before section ```[A]```, when you call ```ini_find_section(ini, "A")```, it returns index of section ```[AB]``` instead of ```[A]```.

This is quite huge bug... Cost me some time, searching through my code what I did wrong and after stepping into everything, I saw this... It should be fixed ASAP.

It affects ```ini_find_section``` and ```ini_find_property``` functions.

**Comment by RandyGaul** [comment]
So what is the fix?

**Comment by WSSDude** [comment]
Line 732 should be changed as I described above.
I probably should have written that, sorry.

Otherwise as I said, some comparisons will return true when they shouldn't if you don't specify size yourself.

**Comment by RandyGaul** [comment]
Hey thanks!

So 732 needs a + 1?

**Comment by WSSDude** [comment]
Yep, that fixed this issue for me.

**Comment by RandyGaul** [comment]
Okay cool I’d love to grab your pull request. I’ve been hooking up ini.h today and am trying to get in these bugfixes. Mattias is slow to incorporate GitHub stuff (I suspect he’s just too old school to get motivated about GitHub).

Some of his ini code isn’t well tested! Except for us that post about bugs here.

**Comment by WSSDude** [comment]
After reading descriptions starting at line 270, I changed my proposed fix a little bit to be compliant with original intention. 

Pull request coming SOON™...

**Comment by WSSDude** [comment]
Accidental close...

**Comment by mattiasgustavsson** [comment]
Fixed
