### ISSUE TITLE
ini.h: Bad bounds checking in ini_find_property()

### ISSUE THREAD

**Issue by oin** [mattiasgustavsson/libs#15]
Currently, `ini_find_property()` loops through properties with this line:

https://github.com/mattiasgustavsson/libs/blob/022370a79cf2d5f87fb43b420834a069adb5fede/ini.h#L755

This runs fine when the property you expect is there, but when it is not the code will run through all uninitialized and unused sections because the loop is bounded by `ini->property_capacity`, not `ini->property_count`. If the section happens to be 1 and the property name string is ill-formed, then the program will crash.

Setting `calloc()` as a custom memory allocator (by defining the `INI_MALLOC` macro) will also get rid of the bad behavior, but in case of a property that doesn't exist in the file there will still be unnecessary iterations (from `ini->property_count` to `ini->property_capacity`).

**Comment by mattiasgustavsson** [comment]
Fixed
