### ISSUE TITLE
In thread.h, MinGW doesn't like VC's __try/__except

### ISSUE THREAD

**Issue by Photosounder** [mattiasgustavsson/libs#18]
In thread.h in thread_create() the _WIN32 code assumes that we're using Visual Studio and uses the Microsoft-specific __try() and __except() to name the thread. Since MinGW's GCC doesn't like it and it's only vaguely needed if you're using Visual Studio I added a #ifdef _MSC_VER around it at line 684 to disable thread naming.

**Comment by mattiasgustavsson** [comment]
Removed thread names in https://github.com/mattiasgustavsson/libs/commit/c60c0afd804155bb71f9b881976f41571d19768d
