### ISSUE TITLE
Bug in ini_property_value_set

### ISSUE THREAD

**Issue by RandyGaul** [mattiasgustavsson/libs#2]
https://github.com/mattiasgustavsson/libs/blob/master/ini.h#L987

It seems the line

    ini->properties[ p ].name[ length ] = '\0';

should be

    ini->properties[ p ].value[ length ] = '\0';

**Comment by RandyGaul** [comment]
Similarly I am guessing (not tested) there is a similar bug here: https://github.com/mattiasgustavsson/libs/blob/master/ini.h#L981

Where

    INI_MEMCPY( ini->properties[ p ].name_large, value, (size_t) length );

should be

    INI_MEMCPY( ini->properties[ p ].value_large, value, (size_t) length );

**Comment by RandyGaul** [comment]
Looks like you copy + pasted the implementation from `ini_property_name_set` and forgot to rename `name` to `value`?

**Comment by mattiasgustavsson** [comment]
Oh, you are quite right! Good catch, will fix.

**Comment by mattiasgustavsson** [comment]
Fixed in version 1.2
