### ISSUE TITLE
In thread.h: thread_create() name conflict on macOS

### ISSUE THREAD

**Issue by Photosounder** [mattiasgustavsson/libs#20]
thread.h fails to compile for me on macOS 10.14 with Xcode because thread.h's `thread_create()` declaration conflicts with the `thread_create` found in the macOS SDK's mach/task.h. Maybe calling it something that's already taken wasn't a good idea?

**Comment by mattiasgustavsson** [comment]
macOS is not really a priority - I think in this case, it can be worked around by  #define/#undef around the thread.h includes
