### ISSUE TITLE
Can't mount as root

### ISSUE THREAD

**Issue by ibachar** [mattiasgustavsson/libs#21]
Hi,

In the documentation it says that in order to mount as root path you can pass an empty string to mount_as. But in the code it checks if the mount_as string is empty and returns an error. Passing "/" causes other problems regarding finding files. Are there any plans to fix these issues?

**Comment by RandyGaul** [comment]
I also ran into this annoying tidbit!

**Comment by mattiasgustavsson** [comment]
Fixed

**Comment by konsumer** [comment]
This is still not working for me, am I doing it wrong?:

```c
assetsys_mount(assetsys, argv[1], "");
// or
assetsys_mount(assetsys, argv[1], NULL);
// or
assetsys_mount(assetsys, argv[1], "/");
```

**Comment by konsumer** [comment]
@mattiasgustavsson Is there a way to mount something on the root?

**Comment by mattiasgustavsson** [comment]
@konsumer Looks like it was broken when mounting a folder as root, but it worked when mounting a zip file as root. I tried making a fix for it, hopefully it didn't break any of the other cases (fingers crossed)

**Comment by konsumer** [comment]
I was trying to mount zip as root. I will make a small repro & test.

**Comment by konsumer** [comment]
Ok, made repro [here](https://github.com/konsumer/assetsys-test). Looks good!

I noticed a couple unrelated things:

- README lists 3 args for `assetsys_file_load`, but should be 5.
- when I list `/` it only shows the zip mounted on root, not the subdir. Is this expected? I can llst them seperately, and it works fine, but I would expect `/` to show files in `/` and `/build`
