### ISSUE TITLE
Function thread_queue_produce always returns zero

### ISSUE THREAD

**Issue by martincohen** [mattiasgustavsson/libs#30]
I hope my eyes are not fooling me, but it looks like `thread_queue_produce` always returns zero. https://github.com/mattiasgustavsson/libs/blob/main/thread.h#L1392

**Comment by outerpassage** [comment]
This is especially confusing given that the documentation specifically states "If the wait timed out, a value of 0 is 
returned, otherwise a non-zero value is returned."

**Comment by mattiasgustavsson** [comment]
I think this was fixed at some point, I just didn't update the issue.
