### ISSUE TITLE
[`thread.h`] : Linux `pthread_setname_np()` not defined

### ISSUE THREAD

**Issue by SuperUserNameMan** [mattiasgustavsson/libs#37]
Got this issue on Linux Mint 20 ( based upon Ubuntu whatever).

GCC will complain `pthread_setname_np()` is missing.

Actually, it is just hidden by default,  because it is "not portable" ( suffix `_np` ).

To make it visible again, one has to add : `#define __USE_GNU`

**Comment by mattiasgustavsson** [comment]
I decided to remove thread naming instead - it is not supported on all platforms, it can cause problems such as this, and I don't find it very useful anyway. https://github.com/mattiasgustavsson/libs/commit/c60c0afd804155bb71f9b881976f41571d19768d
