### ISSUE TITLE
strpool.h - discards all

### ISSUE THREAD

**Issue by zecruel** [mattiasgustavsson/libs#39]
Hi,

In `strpool.h`, is it possible to implement a function to discard all strings in pool?
That is, recycle memory without freeing it, and also without iterating with `strpool_discard` over each handle.

Thank's.

**Comment by mattiasgustavsson** [comment]
I think that would slightly break some of the intended behaviour -  the counter portion of a handle needs to change when the memory for that handle is re-used. I think it is probably better to completely destroy the pool and re-initialize it, if you want to remove all strings, and treating it as an entirely new pool, where none of the old handles are valid.
