### ISSUE TITLE
ini.h: handling property and comment on same line, and handling empty values.

### ISSUE THREAD

**Issue by jwstolk** [mattiasgustavsson/libs#42]
I ran into two issues:

`property =  5  ; test comment` returned `5  ; test comment` as value.

`property =        \n` removed spaces before the value, upto the end of the line, and spaces after the value upto '='.

This resulted in a negative or zero value length. In case of a zero length ini_property_add() would do strlen() to search for the end of the value, which it would find at the end of the file. So for an empty value ALL data upto the end of the file would be returned.
As a workaround I added ini_property_add_empty() which stores 1 byte empty string (just the '\0').

```
            /* property */
            else
                {
                start = ptr;
                while( *ptr && *ptr !='=' && *ptr != '\n' ) ++ptr; // find "="
                if( *ptr == '=' )
                    {
                    len = (int)( ptr - start);
                    ++ptr;
                    while( *ptr && *ptr <= ' ' && *ptr != '\n' ) ptr++;  // this will properly detect start of comment. only the '\n' check is needed since '\n' < ' ')
                    start2 = ptr;
                    while( *ptr                && *ptr != ';' && *ptr != '\n') ++ptr;  // find end of value, upto start of comment or end of line
                    while( *(--ptr) <= ' ' ) (void)ptr;  // ignore traling spaces, tabs, etc. (if there is no value, this will stop back at the "=", causing (ptr - start2) to be negative!
                    ptr++;
					int len2 = (int) ptr - start2; // can be negative beause we skip spaces in both directions!
					if(len2 > 0)
						{
						ini_property_add( ini, s, start, len, start2, len2 ); // (can't handle empty or negative values!)
						}else{
						ini_property_add_empty( ini, s, start, len); // store an empty value.
						}
					// Note: if we removed trailing spaces, they will be skipped in the next pass, and we will detect (and skip) the ";" comment (if any)
                    }
                }

```
I did not do a lot of testing but it works in my case so far, so others may find this helpful.

**Comment by mattiasgustavsson** [comment]
I guess there is no single definition of ini file format. Some allow comments on same line as properties, others require them to be on their own line. As I sometime want to be able to specify strings containing semicolon as property values, I decided to go for the latter version. I would possibly consider having an option to control, but for now, I'll require comments to be on their own line.

The empty value thing is definitely a bug, so that's fixed now, thanks!

**Comment by DBJDBJ** [comment]
# empty != null
