### ISSUE TITLE
app.h sample not building with tcc on Win10

### ISSUE THREAD

**Issue by gooderist** [mattiasgustavsson/libs#44]
The sample is not building with tcc unless I:
1. I use the app.h from the template_project repo
2. Comment out msvc specific last line `extern "C"`
3. Move `#include "app.h"` below `#include <stdlib.h>`

When I try to build without the above steps it gives error:
`app.h:837: error: ')' expected (got "*")`

Compiles just fine with msvc but decided to file an issue for tcc after I saw your tweet about how you liked the workflow.

**Comment by mattiasgustavsson** [comment]
Thanks, fixed in https://github.com/mattiasgustavsson/libs/commit/0971baf78146671bae8a42c7961aa03e02fe272e
