### ISSUE TITLE
What't the point of the way union/struct types are defined in thread.h?

### ISSUE THREAD

**Issue by germaniuss** [mattiasgustavsson/libs#49]
I am fairly new to C coding (several months, though I have coded in C++) and I do not understand many C conventions so bear with me. What is the point of writing the types in thread.h in two passes. You have a union like
```C
union thread_mutex_t 
    { 
    void* align; 
    char data[ 64 ];
    };
```
and then you have a compile time check like this
```C
#pragma warning( push )
#pragma warning( disable: 4214 ) // nonstandard extension used: bit field types other than int
struct x { char thread_mutex_type_too_small : ( sizeof( thread_mutex_t ) < sizeof( CRITICAL_SECTION ) ? 0 : 1 ); }; 
#pragma warning( pop )
```
In the case of the thread_signal_t implementation t is even worse since you also define an internal struct besides the compile time check. So, what is the point in doing that instead of just defining it once? You would not need the compilation check and it would be much clearer.

I had this question since I am currently modifying the thread_signal code so that it can return arbitrary value and not just 1 or 0 so it would act kind of like a listener object that returns an event. It would return a "null" (or equivalent for your type) value if timeout and the value if it did not timeout (which could be another suggestion to add to the code since it would actually be pretty useful and is not that hard to implement with some macro magic.

**Comment by RandyGaul** [comment]
`data` is there to make sure the size of the struct is 64 bytes total. This makes the struct easily support a variety of platforms for different sizes of mutex types. 64 bytes is a good number as it fits with a cache line on modern CPUs very easily. The `align` member helps the compiler to know to align the struct along a pointer-sized boundary. This is another optimization. For example, on 64-bit systems any mutex made on the stack would have 8-byte alignment.

The compile time check is just a sanity check to make sure 64 bytes is big enough.

**Comment by germaniuss** [comment]
Well let's say for the thread_signal_t union type. What is the point of writing data[116], is 116 also a good cache block value? How would I go about writing a macro that supports custom structs inside of the internal thread_internal_signal_t for the value parameter. Should I just increase 116 bytes to a bigger arbitrary number?

I kind of understand the reasoning behind thread_mutex_t however it does not seem that clear to me for thread_signal_t.

**Comment by RandyGaul** [comment]
116 is not a good value to fit within cache lines. It's just the size of an int, a mutex and condition variable. This is basically a semaphore.

You don't need a macro to fit things inside of `char data[SIZE]`. Instead, you should use typecasting like thread.h does. It typecasts. For example `thread_signal_t` is typecasted to `thread_internal_signal_t`, where `thread_internal_signal_t` is defined differently for different platforms, but guaranteed to take up less than or equal to the same number of bytes as `thread_signal_t`.

**Comment by germaniuss** [comment]
Sure but in my case let's say I want to return a custom struct which will be passed as a parameter to `thread_signal_raise`. My idea was something along these lines.

```C
#define thread_signal_t_def(name, T) \
    struct thread_signal_t_##name {..., T value}
#define thread_signal_dec(name, T) \
    ...\
    void thread_signal_raise_##name(thread_signal_t_##name* signal, T data) /* this would return the data for any wait on raise*/ \
    T thread_signal_wait_##name(thread_signal_t_##name* signal, int timeout_ms) /* this returns the data that has been raised*/
    ...
```

Can I even implement this without a macro defining/declaring my functions? How would I do this with just typecasting? I imagine the 116 value should also be increased (and I believe it will not be that much more inefficient because of it)

**Comment by RandyGaul** [comment]
You can use macros like you've shown, and it can be functional, but personally I think it's a bit too complex for the value it's offering back. Usually you don't need such a generic macro. For example in thread.h we can see there's just a couple different ways the internal struct gets defined.

In general the typecasting I mentioned is just on pointers. So you typecast a pointer and interpret the memory differently with -> operator.

If you like you can try writing down a more full and specific example and post it here. I'm happy to help discuss options and whatnot. I know Mattias is a bit of a busy bee, so he probably won't be here to comment for another few months :)

**Comment by germaniuss** [comment]
Sure I'll do a mockup and post it over here. Should I just write it in a separate repo and send a link? I'll write more in depth as to why I need this later and provide some examples since it is a pretty wierd thing to add I imagine.

**Comment by germaniuss** [comment]
Thanks for your time btw! It is very much appreciated.

**Comment by RandyGaul** [comment]
Try using gist, it's great for this sort of thing gist.github.com

**Comment by DBJDBJ** [comment]
Or try using GODBOLT

**Comment by germaniuss** [comment]
@RandyGaul sorry for sending this a day later, life got in the way and since I live in Europe when I was talking to you yesterday it was like 2AM :sweat_smile: Anyways here is the gist https://gist.github.com/germaniuss/afee7af37cdba38ea0dabd0a84e73b32 I was thinking in doing something of the sort (note that I have not tested the code). This approach does look a lot less clean that the way it is already implemented but I truly have no idea on how I would allow for an arbitrary struct return type.

**Comment by RandyGaul** [comment]
Okay I think I see the idea here, but it's definitely too complex and needs to be simplified. I think what may work better is a threadpool and perhaps a ring buffer (or potentially multiple ring buffers). You shouldn't be using any macros. Instead I recommend to try thinking more about memory. You can store bytes in e.g. a ring buffer to sync data across threads. You can leave it up to the user to typecast the memory properly. This way your threading API just deal in bytes. There's no need for your macros to be "templated" for different data types.

**Comment by mattiasgustavsson** [comment]
@germaniuss i think Randy already explained everything about the structs, I just wanted to add that the reason I am doing it like this, is to avoid a dynamic allocation for these simple types, while still hiding implementation details and not leaking system/platform headers to compile units which include the thread.h header part

**Comment by mattiasgustavsson** [comment]
If I understand correctly what you’re trying to do, I agree with randy to use one (or more) ring buffers. Possibly you could use the thread_queue construct in thread.h. The produce/consume functions use a signal to wait for an item to become available or for a slot in the buffer to be free. The queue is a lock-free single producer/single consumer queue. If you need multiple consumers/producers my recommendation would be to implement a locking queue with a mutex
