### ISSUE TITLE
INI_STRICMP should have length as 3rd argument

### ISSUE THREAD

**Issue by bkaradzic** [mattiasgustavsson/libs#5]
Current API that accept `name_length` won't work correctly if string is not nul terminated. Name length implies that it's OK to not be nul terminated, but because `INI_STRICMP` doesn't have length:

```cpp
int ini_find_section( ini_t const* ini, char const* name, int name_length );
int ini_find_property( ini_t const* ini, int section, char const* name, int name_length );
```

My fix was to add length to `INI_STRICMP` usage:

```cpp
if( (int) INI_STRLEN( other ) == name_length && INI_STRICMP( name, other, name_length ) == 0 )
```

**Comment by mattiasgustavsson** [comment]
FIxed in version 1.2
