### ISSUE TITLE
AssetSys: Mount from Memory

### ISSUE THREAD

**Issue by RobLoach** [mattiasgustavsson/libs#53]
Would be awesome to have a `assetsys_mount_memory()` or similar to mount from an already loaded file data.

``` c
assetsys_mount_memory(assetsys_t* sys, void* file_data, uint file_size, char const* mount_as);
```

Would this be out of scope for assetsys?

**Comment by RandyGaul** [comment]
Since it’s using minizip mounting a zip file from memory could be fairly easy. But for folders it would be significantly more work

**Comment by mattiasgustavsson** [comment]
If someone made a PR for it, I wouldn’t mind adding it (assuming it’s done in a way consistent with the library overall), but it’s not something I’d have the time to do myself
